### PR TITLE
Upgrade tech docs gem to v4.1.1

### PR DESCRIPTION
**Pull request by kr8n3r**
Upgrade tech-docs-gem to v4.1.1 along with other dependencies
Import v5 of the govuk-frontend as per release notes

Test locally - https://github.com/alphagov/notifications-tech-docs?tab=readme-ov-file#docker-container

Screenshot 2024-11-12 at 10 10 48

### CODE REVIEW

**Review by tombye — CHANGES_REQUESTED** [review]
Mostly looks good but I spotted the links in the table of contents have this extra focus ring:

image
image

**Comment by kr8n3r** [comment]
hmm, that looks like it's been there for a while. i'll have a look if it's extra local styling or upstream fix required

**Comment by kr8n3r** [comment]
@tombye upgraded to v4.1.1 which brings in the fix - https://github.com/alphagov/tech-docs-gem/releases/tag/v4.1.1

**Review by tombye — APPROVED** [review]
No sign of the extra outline now. Thanks for all the work involved in fixing it 👍🏻

**Pull request merged**
