### PR TITLE
Rewrite README and consolidate tasks

### PR DESCRIPTION
**Pull request by benthorner**
Contributes to: https://github.com/alphagov/notifications-manuals/issues/9

This makes a fairly major change by switching the local development approach
to Docker. I've tried to isolate that change in the last commit, so it's easy
to roll back if we decide we don't like it.

### CODE REVIEW

**Review by quis — APPROVED** [review]
Documentation changes seem sensible. Tested the docker commands locally and they work. Not sure if live reload ever worked before, but it doesn’t seem to now (however I’m not about to mess around with various incantations of `gem rbenv bundle` to try to find out, which probably indicates moving to Docker is a good thing).

**Comment by benthorner** [comment]
Thanks for the review @quis!

> Not sure if live reload ever worked before

That's interesting. I just tried locally and I'm able to update the source files and see those changes when I refresh. There's not much code to this app and middleman won't auto-reload if it changes - is that what you meant? Or maybe you meant the "LiveReload" it talks about when it starts. That's for changes to the source files e.g.

```
== LiveReloading path: /rest-api.html
== LiveReloading path: /client_template.html
== LiveReloading path: /documentation/index
== LiveReloading path: /accessibility.html
```

Does that help?

**Comment by quis** [comment]
Live reload is when it automatically refreshes the page whenever you make changes to a file. No need to press the refresh button yourself. Uses websockets somehow. We don’t have it in any of our other apps so I’m not that fussed about having/keeping it here.

**Comment by benthorner** [comment]
Aha, I see what you mean now. I did work before (just checked) and while I agree it's not critical, it's not that hard to keep it working. I've added a new commit to do just that (https://github.com/alphagov/notifications-tech-docs/pull/159/commits/253a3a2546086cc12b5fa4596dc666a13e37e241). Do you want to try it out?

**Review by quis — APPROVED** [review]
Nice one, tested the live reload locally and it works. Double approval 👍🏻 👍🏻

**Pull request merged**
